initialLearningRate = 0.001;
dropFactor = 0.5;
dropPeriod = 50;

options = trainingOptions('adam', ...
    'MaxEpochs', 100, ...
    'MiniBatchSize', 32, ...
    'ValidationFrequency', 200, ...
    'Verbose', true, ...
    'Plots', 'training-progress', ...
    'InitialLearnRate', initialLearningRate, ...
    'LearnRateSchedule', 'piecewise', ...
    'Shuffle','every-epoch', ...
    'LearnRateDropFactor', dropFactor, ...
    'LearnRateDropPeriod', dropPeriod);